In [9]:
import pandas as pd
import numpy as np
dict={
    "name":["Samarpan Poudel","Suraksha Poudel"],
    "age":[19, 27],
    "Gender":["M","F"],
    "Caste":["Hindu","Hindu"],
    "Country of citizenship":["Nepal","Nepal"]
     
}
df = pd.DataFrame(dict) #it creates storage in python similar like excel
df #Should pass data in the list

              name  age Gender  Caste Country of citizenship
0  Samarpan Poudel   19      M  Hindu                  Nepal
1  Suraksha Poudel   27      F  Hindu                  Nepal

In [10]:
#In order to access it in a excel sheet 
df.to_csv("Introduction.csv")

In [13]:
df.head(1)  #Show first row only as it is passed 1

              name  age Gender  Caste Country of citizenship
0  Samarpan Poudel   19      M  Hindu                  Nepal

In [14]:
df.tail(1) #shows last one only

              name  age Gender  Caste Country of citizenship
1  Suraksha Poudel   27      F  Hindu                  Nepal

In [15]:
df.describe() #performs statstistical operations

             age
count   2.000000
mean   23.000000
std     5.656854
min    19.000000
25%    21.000000
50%    23.000000
75%    25.000000
max    27.000000

In [19]:
#To open external file data
external_data=pd.read_csv("IPL.csv")
external_data

  IPL Teams  Trophy
0       CSK       5
1       RCB       0
2        MI       5
3       KKR       3